decodeのコード書けた。こんな感じで動く:
```sql
my_extension=# DROP EXTENSION my_extension; CREATE EXTENSION my_extension;
ERROR:  extension "my_extension" does not exist
CREATE EXTENSION
my_extension=# select ENCAVG(c) from t;
ERROR:  function encavg(integer) does not exist
LINE 1: select ENCAVG(c) from t;
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
my_extension=# create table t2 (c_enc EncInteger);
CREATE TABLE
my_extension=# insert into t2 (c_enc) values (1);
ERROR:  column "c_enc" is of type encinteger but expression is of type integer
LINE 1: insert into t2 (c_enc) values (1);
                                       ^
HINT:  You will need to rewrite or cast the expression.
my_extension=# insert into t2 (c_enc) values ('{ base64: "1" }');
ERROR:  failed to deserialize json: Error("key must be a string", line: 1, column: 3)
LINE 1: insert into t2 (c_enc) values ('{ base64: "1" }');
                                       ^
CONTEXT:  /Users/sho.nakatani/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-0.1.21/src/inoutfuncs.rs:46:14
my_extension=# insert into t2 (c_enc) values ('{ "base64": "1" }');
INSERT 0 1
my_extension=# select ENCAVG(c_enc) from t2;
ERROR:  called `Result::unwrap()` on an `Err` value: DecodeError("Encoded text cannot have a 6-bit remainder.")
CONTEXT:  src/enclave/enc_integer_avg/func.rs:12:38
```